# Site settings
title: Qingshuo's Homepage
description: Latex does not display properly in my blog.
url: "https://qsongatwpi.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: Qingshuo Song
  email: qsong@wpi.edu
