# Site settings
title: Qingshuo's Homepage
description: I am Qingshuo Song.
url: "https://qsongatwpi.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: Qingshuo Song
  email: qsong@wpi.edu

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mathjax

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

# Social media settings
github_username: qsongatwpi
